- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      command: pwd
      register: hello
    - debug: msg="{{ hello.stdout }}" 
    - debug: msg="{{ hello.stderr }}"
    - name: Creating a file
      file:
        path: "/home/akhizar1/helloworld.txt"
        state: touch
      become: yes
      become_user: akhizar1
    - name: Hello Text
      command: ls -l
      register: hello1
    - debug: msg="{{ hello1.stdout }}" 
    - debug: msg="{{ hello1.stderr }}"
