- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      command: pwd
    - name: Creating a file
      file:
        path: "helloworld.txt"
        state: touch
      become: yes
