- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: Creating a file
      file:
        path: "helloworld.txt"
        state: touch
      become: yes
